[workspace]
resolver = "2"
members = [
    "central",
    "remote",
    "quic-common",
    "quic-metrics",
    "quic-video",
    "onvif-server",
    "onvif-client",
    "admin-web",
    "ffmpeg-recorder",
    "recording-retrieval",
    "config-manager",
    "remote-setup",
    "central-setup",
]
